# https://github.com/marketplace/actions/install-nix

name: "ci-nix"
on:
  pull_request:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Install nix
      uses: cachix/install-nix-action@v27

    # Possibly need to cache cabal.
    - name: Cache .cabal
      uses: actions/cache@v3
      with:
        path: ${{ steps.cabal-setup.outputs.cabal-store }}
        key: cabal-${{ hashFiles('cabal.project') }}

    # We currently do not have a default target
    - run: nix build --accept-flake-config .#wst-poc
    - run: nix flake --accept-flake-config check

