name: "ci-ui"
on:
  pull_request:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 23
    - run: |
        cd frontend
        npm install
        npm run export
